version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate && gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    expose:
      - "8000"
    env_file:
      - .env

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app

  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
    command: celery -A backend worker -l info
    volumes:
      - .:/code
    depends_on:
      - redis
    env_file:
      - .env
