version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=test
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  backend:
    build: backend/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: frontend/
    command: npm start
    volumes:
      - ./:/app
      - /app/frontend/node_modules
    ports:
      - "3000:3000"

