# Generated by Django 4.0.2 on 2022-04-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_music_service', '0007_rename_created_date_comment_created_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(null=True),
        ),
    ]
