# Generated by Django 4.0.2 on 2022-04-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_music_service', '0008_song_lyrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('table', models.CharField(max_length=65)),
                ('record_id', models.BigIntegerField()),
                ('column_name', models.CharField(max_length=65)),
                ('old_value', models.TextField(null=True)),
                ('new_value', models.TextField(null=True)),
            ],
            options={
                'db_table': 'simple_music_service_database_audit',
            },
        ),
    ]
