# Generated by Django 4.0.2 on 2022-04-25 13:14

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import simple_music_service.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('simple_music_service', '0009_databaseaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(simple_music_service.models.DatabaseAuditMixin, 'auth.user'),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='simple_music_service.applicationuser'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_music_service.applicationuser'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_music_service.applicationuser'),
        ),
        migrations.AlterField(
            model_name='song',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_music_service.applicationuser'),
        ),
    ]
