# Generated by Django 4.0.2 on 2022-05-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_music_service', '0010_applicationuser_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='deleted_date_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='deleted_date_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='deleted_date_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='deleted_date_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='deleted_date_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
