# Generated by Django 4.0.2 on 2022-05-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_music_service', '0013_songplaylist_artistsong_transfer_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_date_time__isnull', True)), fields=('name',), name='unique_artist_name'),
        ),
    ]
