# Generated by Django 4.0.1 on 2022-01-31 13:11

from django.db import migrations, models
from typing import List


class Migration(migrations.Migration):

    initial = True

    dependencies: List[str] = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("artist", models.CharField(max_length=50)),
                ("year", models.DateField()),
                ("location", models.CharField(max_length=100)),
            ],
        ),
    ]
